MsgDataPool
MsgData* MsgDataPool::pool
Array of MsgData objects.
Referenced by allocate, deallocate, initialize, ~MsgDataPool.
uint8_t MsgDataPool::poolSize
Current pool size.
Referenced by allocate, getPoolSize, initialize, updateAdaptiveLimit.
uint8_t MsgDataPool::poolLimit
Maximum pool size.
Referenced by allocate, getPoolLimit, initialize, updateAdaptiveLimit.
uint8_t MsgDataPool::currentInUse
Number of messages currently in use.
Referenced by allocate, deallocate, getCurrentInUse, initialize, updateAdaptiveLimit.
uint8_t MsgDataPool::nextFree
Index of next free message.
Referenced by allocate.
MsgDataPool::MsgDataPool()
Constructor.
Initializes the message pool with default settings
MsgDataPool::~MsgDataPool()
Destructor.
Frees all allocated memory
References pool.
MsgData * MsgDataPool::allocate()
Allocate a new MsgData from the pool.
Pointer to allocated MsgData, or nullptr if pool is full Returns nullptr if no memory available
References MemoryStats::current_usage, currentInUse, fsmos_memory_stats, initialize, nextFree, MemoryStats::peak_usage, pool, poolLimit, poolSize, MemoryStats::total_allocated, updateAdaptiveLimit.
void MsgDataPool::deallocate(MsgData *msg)
Return a MsgData to the pool.
msg Pointer to MsgData to deallocate Frees any associated data and returns MsgData to pool
References MemoryStats::current_usage, currentInUse, fsmos_memory_stats, pool, MemoryStats::total_freed, updateAdaptiveLimit.
Referenced by SharedMsg::operator=, SharedMsg::release.
void MsgDataPool::updateAdaptiveLimit()
Update adaptive pool limit based on usage.
Automatically adjusts pool size for optimal performance
References currentInUse, poolLimit, poolSize.
Referenced by allocate, deallocate.
uint8_t MsgDataPool::getPoolSize() const
Get current pool size.
Current number of MsgData objects in pool
References poolSize.
uint8_t MsgDataPool::getPoolLimit() const
Get maximum pool limit.
Maximum number of MsgData objects allowed
References poolLimit.
uint8_t MsgDataPool::getCurrentInUse() const
Get number of currently allocated messages.
Number of messages currently in use
References currentInUse.
bool MsgDataPool::initialize()
Initialize the message pool if not already initialized.
true if pool was initialized successfully, false if already initialized or failed This method performs lazy initialization to avoid static allocation issues
References currentInUse, fsmos_memory_stats, Scheduler::LOG_ERROR, Scheduler::logMessage, OS, pool, poolLimit, poolSize, MemoryStats::total_allocated.
Referenced by allocate.