Task
Priority
Lowest priority (0)
State
Task is not running.
friend class Scheduler
uint16_t Task::remainingTime
Remaining time until next execution (in ms)
Referenced by Scheduler::executeTaskStep, Scheduler::findNextTask, Scheduler::loopOnce, resume, start.
uint16_t Task::periodMs
Task execution period in milliseconds.
Referenced by getPeriod, resume, setPeriod, start.
uint8_t Task::taskId
Unique task identifier.
Referenced by Scheduler::add, getId.
uint8_t Task::stateAndPriority
Combined state and priority (4 bits each)
Referenced by getPriority, getState, setPriority, setPriority, setState.
const __FlashStringHelper* Task::name
Task name for debugging.
Referenced by getName, setName.
uint16_t Task::runCount
Number of times task has run (16-bit for space)
Referenced by Scheduler::getTaskStats, Scheduler::updateTaskStatistics.
uint16_t Task::maxExecTimeUs
Maximum execution time in microseconds (16-bit)
Referenced by Scheduler::getTaskStats, Scheduler::updateTaskStatistics.
uint16_t Task::avgExecTimeUs
Average execution time in microseconds (16-bit)
Referenced by Scheduler::getTaskStats, Scheduler::updateTaskStatistics.
uint32_t Task::scheduledTime
When this task was scheduled to run.
Referenced by getScheduledTime, Scheduler::handleTaskTiming.
uint32_t Task::actualStartTime
When this task actually started running.
Referenced by getActualStartTime, Scheduler::handleTaskTiming.
uint16_t Task::delayCount
Number of times this task was delayed.
Referenced by getDelayCount, Scheduler::getTaskStats, Scheduler::handleTaskTiming.
uint16_t Task::maxDelayMs
Maximum delay experienced in milliseconds.
Referenced by getMaxDelay, Scheduler::getTaskStats, Scheduler::handleTaskTiming.
TopicBitfield Task::subscribedTopics
Bitfield for subscribed topics.
Referenced by Scheduler::getSystemMemoryInfo, Scheduler::getTaskMemoryInfo, getTopicCount, isSubscribedToTopic, subscribe, unsubscribe.
uint8_t Task::maxMessageBudget
Referenced by getConfiguredMessageBudget, setMaxMessageBudget.
uint16_t Task::createdInstanceCount
Referenced by getCreatedInstanceCount, Task, ~Task.
Task::Task(const __FlashStringHelper *name=nullptr)
Constructor.
name Optional name for the task (for debugging) Creates a new task in INACTIVE state
References createdInstanceCount.
Task::~Task()
Virtual destructor.
Ensures proper cleanup of derived classes
References createdInstanceCount.
virtual void Task::on_start()
Called when task is started.
Override this method to perform initialization Called once when task transitions to ACTIVE state
Referenced by start.
virtual void Task::step()=0
Main task execution method.
This method is called periodically by the scheduler Must be implemented by derived classes
Referenced by Scheduler::executeTaskStep.
virtual void Task::on_stop()
Called when task is stopped.
Override this method to perform cleanup Called when task transitions to INACTIVE state
Referenced by stop.
virtual void Task::on_msg(const MsgData &msg)
Handle incoming messages.
msg The received message Override this method to handle specific message types Called automatically when messages are received
Referenced by Scheduler::processMessages.
void Task::start()
Start the task.
Transitions task to ACTIVE state and calls on_start()
References ACTIVE, getState, INACTIVE, on_start, periodMs, remainingTime, setState.
Referenced by Scheduler::begin.
void Task::stop()
Stop the task.
Transitions task to INACTIVE state and calls on_stop()
References ACTIVE, getState, INACTIVE, on_stop, setState, SUSPENDED.
Referenced by Scheduler::removeAll.
void Task::suspend()
Suspend the task.
Task remains in memory but is not scheduled
References ACTIVE, getState, setState, SUSPENDED.
void Task::resume()
Resume the task.
Task returns to scheduling queue
References ACTIVE, getState, periodMs, remainingTime, setState, SUSPENDED.
void Task::terminate()
Terminate the task.
Marks task for removal from scheduler
References setState, TERMINATED.
void Task::setPeriod(uint16_t period_ms)
Set task execution period.
period_ms Period in milliseconds Minimum period is 1ms, maximum is 65535ms
References MAX_TASK_PERIOD, MIN_TASK_PERIOD, periodMs.
uint16_t Task::getPeriod() const
Get task execution period.
Period in milliseconds
References periodMs.
Referenced by Scheduler::executeTaskStep, Scheduler::getTaskStats, Scheduler::handleTaskTiming.
void Task::setPriority(Priority priority)
Set task priority.
priority Priority level Sets the task priority for scheduling
References stateAndPriority.
void Task::setPriority(uint8_t priority)
Set task priority (legacy)
priority Priority level (0-15) Sets the task priority for scheduling
References stateAndPriority.
uint8_t Task::getPriority() const
Get task priority.
Priority level
References stateAndPriority.
Referenced by Scheduler::findNextTask, Scheduler::getTaskStats.
void Task::setMaxMessageBudget(uint8_t budget)
Declare the maximum number of messages this task may produce in one step()
Used by the scheduler to avoid running producers when the global message queue has fewer free slots than the declared budget. 0 disables gating.
References maxMessageBudget.
virtual uint16_t Task::getTaskStructSize() const
Get the size in bytes of the concrete task object.
Implement in each derived Task as: return sizeof(DerivedClass);
Referenced by Scheduler::getSystemMemoryInfo, Scheduler::getTaskMemoryInfo.
static uint16_t Task::getCreatedInstanceCount()
Get total number of Task instances ever created.
References createdInstanceCount.
Referenced by Scheduler::initializeTaskNodePool.
static const __FlashStringHelper * Task::readTaskName(const Task *t)
Public helper to read another task's name safely from diagnostics.
References getName.
uint8_t Task::getConfiguredMessageBudget() const
Access the configured budget set via setMaxMessageBudget()
The configured budget value
References maxMessageBudget.
Task::State Task::getState() const
Get current task state.
Current state of the task
References stateAndPriority.
Referenced by Scheduler::checkForTerminatedTask, checkState, Scheduler::getTaskStats, isActive, isInactive, resume, start, stop, suspend.
void Task::setState(State newState)
Set task state.
newState New state to set
References stateAndPriority.
Referenced by resume, start, stop, suspend, terminate.
bool Task::checkState(State expected) const
Check if task is in expected state.
expected Expected state to check against true if task is in expected state
References getState.
bool Task::isActive() const
Check if task is active.
true if task is in ACTIVE state
References ACTIVE, getState.
Referenced by Scheduler::executeTask, Scheduler::findNextTask, Scheduler::loopOnce, Scheduler::processMessages, Scheduler::publishMessage, Scheduler::sendMessage.
bool Task::isInactive() const
Check if task is inactive.
true if task is in INACTIVE state
References getState, INACTIVE.
uint8_t Task::getId() const
Get unique task ID.
Task ID assigned by scheduler
References taskId.
Referenced by Scheduler::findNextTask, Scheduler::getMostDelayingTask, Scheduler::getTask, Scheduler::getTaskMemoryInfo, Scheduler::getTaskStats, Scheduler::logMessage, Scheduler::logMessage, Scheduler::updateTimingVariables.
const __FlashStringHelper * Task::getName() const
Get task name.
Task name string
References name.
Referenced by Scheduler::getTaskStats, readTaskName.
void Task::setName(const __FlashStringHelper *name)
Set task name.
name New name for the task
References name.
void Task::subscribe(uint8_t topic)
Subscribe to a message topic.
topic Topic ID to subscribe to Task will receive messages published to this topic
References MAX_TOPICS, subscribedTopics.
void Task::unsubscribe(uint8_t topic)
Unsubscribe from a message topic.
topic Topic ID to unsubscribe from
References MAX_TOPICS, subscribedTopics.
bool Task::isSubscribedToTopic(uint8_t topic) const
Check if task is subscribed to a topic.
topic Topic ID to check true if subscribed, false otherwise
References MAX_TOPICS, subscribedTopics.
Referenced by Scheduler::publishMessage.
uint8_t Task::getTopicCount() const
Get the number of subscribed topics.
Number of subscribed topics
References subscribedTopics.
void Task::publish(uint8_t topic, uint8_t type, uint16_t arg=0)
Publish a message to a topic.
topic Topic ID to publish to type Message type arg Additional argument data All subscribed tasks will receive this message
References OS, Scheduler::publishMessage.
void Task::tell(uint8_t task_id, uint8_t type, uint16_t arg=0)
Send a direct message to a specific task.
task_id ID of target task type Message type arg Additional argument data
References OS, Scheduler::sendMessage.
void Task::log(const __FlashStringHelper *msg)
Log an info message.
msg Message to log
References Scheduler::LOG_INFO, Scheduler::logMessage, OS.
void Task::logDebug(const __FlashStringHelper *msg)
Log a debug message.
msg Message to log
References Scheduler::LOG_DEBUG, Scheduler::logMessage, OS.
void Task::logInfo(const __FlashStringHelper *msg)
Log an info message.
msg Message to log
References Scheduler::LOG_INFO, Scheduler::logMessage, OS.
void Task::logWarn(const __FlashStringHelper *msg)
Log a warning message.
msg Message to log
References Scheduler::LOG_WARN, Scheduler::logMessage, OS.
void Task::logError(const __FlashStringHelper *msg)
Log an error message.
msg Message to log
References Scheduler::LOG_ERROR, Scheduler::logMessage, OS.
template Timer32 Task::createTimerTyped< Timer32 >(uint32_t duration_ms) const
Create a memory-optimized timer.
T Timer type (Timer8, Timer16, Timer32) duration_ms Duration in milliseconds Timer object ready to use Choose timer type based on expected duration for memory optimization
void Task::processMessages()
Process pending messages for this task.
Called automatically by scheduler, rarely needs direct use
uint16_t Task::getDelayCount() const
Get number of times this task was delayed.
Number of delay occurrences
References delayCount.
Referenced by Scheduler::getMostDelayingTask.
uint16_t Task::getMaxDelay() const
Get maximum delay experienced by this task.
Maximum delay in milliseconds
References maxDelayMs.
uint32_t Task::getScheduledTime() const
Get scheduled execution time.
Scheduled time in milliseconds
References scheduledTime.
uint32_t Task::getActualStartTime() const
Get actual start time of last execution.
Actual start time in milliseconds
References actualStartTime.