Scheduler
LogLevel
Debug level messages.
TaskNode* Scheduler::taskHead
Head of task linked list.
Referenced by add, findNextTask, findTask, forEachTask, getMostDelayingTask, getSystemMemoryInfo, remove, removeAll, Scheduler.
TaskNode* Scheduler::taskTail
Tail of task linked list.
Referenced by add, remove, removeAll, Scheduler.
TaskNode* Scheduler::freeTaskNodeHead
Head of free-list for TaskNode pool.
Referenced by allocateTaskNode, deallocateTaskNode, initializeTaskNodePool.
bool Scheduler::taskNodePoolInitialized
Whether pool has been initialized.
Referenced by allocateTaskNode, initializeTaskNodePool.
uint16_t Scheduler::taskNodePoolCapacity
Total nodes currently allocated to pool/list.
Referenced by allocateTaskNode, getMaxTasks, initializeTaskNodePool.
uint8_t Scheduler::taskCount
Current number of tasks.
Referenced by add, getSystemMemoryInfo, getTaskCount, remove, removeAll.
uint8_t Scheduler::nextTaskId
Next available task ID.
Referenced by add.
MsgDataPool Scheduler::msgPool
Message pool for efficient allocation.
Referenced by SharedMsg::operator=, SharedMsg::release.
uint32_t Scheduler::systemTime
Current system time.
Referenced by begin, executeTask, getResetInfo, now, onTick, updateSystemTime, updateTimingVariables.
bool Scheduler::running
Scheduler running state.
Referenced by begin, loop, loopOnce, stop.
LogLevel Scheduler::currentLogLevel
Current minimum log level.
Referenced by logMessage, logMessage, setLogLevel.
uint8_t Scheduler::lastExecutedTaskId
ID of last executed task (for delay attribution)
Referenced by handleTaskTiming, updateTimingVariables.
uint32_t Scheduler::lastTaskEndTime
When the last task finished execution.
Referenced by updateTimingVariables.
MsgNode* Scheduler::msgHead
Referenced by dequeueQueuedMessage, dequeueQueuedMessageNode, enqueueQueuedMessage, getSystemMemoryInfo, processMessages.
MsgNode* Scheduler::msgTail
Referenced by dequeueQueuedMessage, dequeueQueuedMessageNode, enqueueQueuedMessage, processMessages.
MsgNode* Scheduler::freeHead
Referenced by allocateMsgNode, allocateMsgNodesChunk, deallocateMsgNode, enqueueQueuedMessage, getSystemMemoryInfo, processMessages.
uint8_t Scheduler::msgCount
Referenced by dequeueQueuedMessage, dequeueQueuedMessageNode, enqueueQueuedMessage, getFreeQueueSlots, getSystemMemoryInfo, processMessages.
uint8_t Scheduler::totalNodes
Referenced by allocateMsgNodesChunk.
friend class SharedMsg
Allow SharedMsg to access msgPool.
Scheduler::Scheduler()
Constructor.
Initializes scheduler with default settings
References taskHead, taskTail.
Scheduler::~Scheduler()
Destructor.
Removes all tasks and cleans up resources
References removeAll.
bool Scheduler::add(Task *task)
Add a task to the scheduler.
task Pointer to task to add true if task was added successfully, false if scheduler is full Task starts in INACTIVE state
References allocateTaskNode, LOG_ERROR, logInfof, logSystemEvent, MAX_TOPICS, TaskNode::next, nextTaskId, taskCount, taskHead, Task::taskId, taskTail.
bool Scheduler::remove(Task *task)
Remove a task from the scheduler.
task Pointer to task to remove true if task was removed, false if not found
References deallocateTaskNode, TaskNode::next, TaskNode::task, taskCount, taskHead, taskTail.
Referenced by checkForTerminatedTask.
void Scheduler::removeAll()
Remove all tasks from the scheduler.
Stops and removes all tasks
References deallocateTaskNode, TaskNode::next, Task::stop, TaskNode::task, taskCount, taskHead, taskTail.
Referenced by ~Scheduler.
Task * Scheduler::getTask(uint8_t task_id)
Get task by ID.
task_id ID of task to find Pointer to task, or nullptr if not found
References findTask, Task::getId.
Referenced by getTaskMemoryInfo, getTaskStats, processMessages, sendMessage.
uint8_t Scheduler::getTaskCount() const
Get number of active tasks.
Number of tasks currently in scheduler
References taskCount.
uint16_t Scheduler::getMaxTasks() const
Get maximum number of tasks.
Maximum number of tasks supported
References taskNodePoolCapacity.
void Scheduler::begin()
Start the scheduler.
Starts all tasks and begins scheduling
References feedWatchdog, forEachTask, LOG_INFO, logSystemEvent, running, setLogLevel, Task::start, systemTime.
void Scheduler::loopOnce()
Execute one scheduling step.
Processes messages and executes one ready task
References executeTask, feedWatchdog, findNextTask, forEachTask, Task::isActive, processMessages, Task::remainingTime, running, updateSystemTime.
Referenced by loop.
void Scheduler::loop()
Run scheduler continuously.
Runs scheduler until stop() is called
References loopOnce, running.
void Scheduler::stop()
Stop the scheduler.
Stops all tasks and halts scheduling
References running.
void Scheduler::publishMessage(uint8_t topic, uint8_t type, uint16_t arg=0)
Publish a message to a topic.
topic Topic ID to publish to type Message type arg Additional argument data All tasks subscribed to the topic will receive this message
References forEachTask, Task::isActive, Task::isSubscribedToTopic.
Referenced by Task::publish.
void Scheduler::sendMessage(uint8_t task_id, uint8_t type, uint16_t arg=0)
Send a direct message to a specific task.
task_id ID of target task type Message type arg Additional argument data
References enqueueQueuedMessage, getTask, Task::isActive.
Referenced by Task::tell.
uint8_t Scheduler::getFreeQueueSlots() const
Get number of free slots in the global message queue.
References MAX_MESSAGE_POOL_SIZE, msgCount.
Referenced by findNextTask.
uint32_t Scheduler::now() const
Get current system time.
Current time in milliseconds
References systemTime.
uint16_t Scheduler::getFreeMemory() const
Get amount of free memory.
Free memory in bytes AVR-specific implementation
Referenced by getSystemMemoryInfo.
void Scheduler::setLogLevel(LogLevel level)
Set minimum log level.
level Minimum level to display Messages below this level will be filtered out
References currentLogLevel.
Referenced by begin.
void Scheduler::logMessage(Task *task, LogLevel level, const char *msg)
Log a message.
task Task that generated the message (can be nullptr) level Log level msg Message to log
References currentLogLevel, Task::getId, LOG_ERROR, LOG_INFO, LOG_WARN.
Referenced by MsgDataPool::initialize, Task::log, Task::logDebug, Task::logError, logFormatted, logFormattedV, Task::logInfo, logSystemEvent, Task::logWarn.
void Scheduler::logMessage(Task *task, LogLevel level, const __FlashStringHelper *msg)
References currentLogLevel, Task::getId, LOG_ERROR, LOG_INFO, LOG_WARN.
void Scheduler::onTick()
Handle system tick.
Called by system timer interrupt Updates internal system time
References systemTime.
bool Scheduler::getResetInfo(ResetInfo &info)
Get system reset information.
info Reference to store reset information true if reset info was retrieved successfully
References getResetCause, getResetCauseFlags, ResetInfo::lastTaskId, ResetInfo::optibootResetCause, ResetInfo::optibootResetFlags, ResetInfo::resetReason, ResetInfo::resetTime, systemTime, ResetInfo::watchdogTimeout.
ResetCause Scheduler::getResetCause()
Get reset cause from system.
ResetCause enumeration value Combines Optiboot and other reset sources
References getResetCauseFlags, RESET_BROWN_OUT, RESET_CAUSE_BROWN_OUT, RESET_CAUSE_EXTERNAL, RESET_CAUSE_POWER_ON, RESET_CAUSE_WATCHDOG, RESET_EXTERNAL, RESET_MULTIPLE, RESET_POWER_ON, RESET_UNKNOWN, RESET_WATCHDOG.
Referenced by getResetInfo, wasResetCause.
uint8_t Scheduler::getResetCauseFlags()
Get raw reset flags from system.
Raw reset flags byte Internal method for reset cause processing
Referenced by getResetCause, getResetInfo.
bool Scheduler::wasResetCause(ResetCause cause)
Check if a specific reset cause occurred.
cause Reset cause to check for true if the specified cause occurred
References getResetCause.
bool Scheduler::getTaskStats(uint8_t task_id, TaskStats &stats)
Get task statistics.
task_id ID of task to get stats for stats Reference to store task statistics true if stats were retrieved successfully
References Task::avgExecTimeUs, TaskStats::delayCount, Task::delayCount, Task::getId, Task::getName, Task::getPeriod, Task::getPriority, Task::getState, getTask, TaskStats::maxDelayMs, Task::maxDelayMs, TaskStats::maxExecTimeUs, Task::maxExecTimeUs, TaskStats::name, TaskStats::periodMs, TaskStats::priority, TaskStats::runCount, Task::runCount, TaskStats::stackUsage, TaskStats::state, TaskStats::taskId, TaskStats::totalExecTimeUs.
bool Scheduler::getSystemMemoryInfo(SystemMemoryInfo &info)
Get system memory information.
info Reference to store memory information true if memory info was retrieved successfully
References SystemMemoryInfo::activeMessages, Scheduler::QueuedMessage::capacity, SystemMemoryInfo::eepromFree, SystemMemoryInfo::eepromUsed, SystemMemoryInfo::flashFree, SystemMemoryInfo::flashUsed, freeHead, SystemMemoryInfo::freeRam, getFreeMemory, Task::getTaskStructSize, SystemMemoryInfo::heapFragments, SystemMemoryInfo::heapSize, SystemMemoryInfo::largestBlock, SystemMemoryInfo::messageMemory, msgCount, msgHead, TaskNode::next, Scheduler::MsgNode::next, Scheduler::MsgNode::payload, SystemMemoryInfo::stackFree, SystemMemoryInfo::stackSize, SystemMemoryInfo::stackUsed, Task::subscribedTopics, TaskNode::task, taskCount, taskHead, SystemMemoryInfo::taskMemory, SystemMemoryInfo::totalRam, SystemMemoryInfo::totalTasks.
bool Scheduler::getTaskMemoryInfo(uint8_t task_id, TaskMemoryInfo &info)
Get task memory information.
task_id ID of task to get memory info for info Reference to store task memory information true if memory info was retrieved successfully
References Task::getId, getTask, Task::getTaskStructSize, TaskMemoryInfo::queue_size, Task::subscribedTopics, TaskMemoryInfo::subscription_size, TaskMemoryInfo::task_id, TaskMemoryInfo::task_struct_size, TaskMemoryInfo::total_allocated.
uint8_t Scheduler::getHeapFragmentation()
Get heap fragmentation percentage.
Heap fragmentation as percentage (0-100)
bool Scheduler::getMemoryLeakStats(MemoryStats &stats)
Get memory leak detection statistics.
stats Reference to store memory leak statistics true if stats were retrieved successfully
References fsmos_memory_stats.
void Scheduler::enableWatchdog(uint8_t timeout)
Enable hardware watchdog timer.
timeout Watchdog timeout value AVR-specific feature
void Scheduler::feedWatchdog()
Referenced by begin, loopOnce.
void Scheduler::logFormatted(Task *task, LogLevel level, const __FlashStringHelper *format,...)
Log a formatted message.
task Task that generated the message (can be nullptr) level Log level format Format string (FlashStringHelper) ... Variable arguments for formatting Simplified implementation - just logs the format string
References logMessage.
uint8_t Scheduler::getMostDelayingTask() const
Get task that caused the most delays.
Task ID of the task causing most delays, or 0 if none
References Task::getDelayCount, Task::getId, TaskNode::next, TaskNode::task, taskHead.
void Scheduler::processMessages()
Process pending messages for all tasks.
Internal method called by step()
References freeHead, getTask, Task::isActive, Scheduler::QueuedMessage::msg, msgCount, msgHead, msgTail, Scheduler::MsgNode::next, Task::on_msg, Scheduler::MsgNode::payload, Scheduler::QueuedMessage::targetTaskId.
Referenced by loopOnce.
void Scheduler::updateSystemTime()
Update system time.
Internal method to update system time from millis()
References systemTime.
Referenced by loopOnce.
Task * Scheduler::findNextTask()
Find next task to execute.
Pointer to next task to execute, or nullptr if none ready
References DEFAULT_TASK_MESSAGE_BUDGET, getFreeQueueSlots, Task::getId, Task::getMaxMessageBudget, Task::getPriority, Task::isActive, TaskNode::next, Task::remainingTime, TaskNode::task, taskHead.
Referenced by loopOnce.
void Scheduler::executeTask(Task *task)
Execute a task.
task Task to execute Updates task timing and calls task->step()
References checkForTerminatedTask, executeTaskStep, handleTaskTiming, Task::isActive, systemTime, updateTaskStatistics, updateTimingVariables.
Referenced by loopOnce.
void Scheduler::handleTaskTiming(Task *task, uint32_t currentTime)
Handle task timing monitoring.
task Task to monitor currentTime Current system time
References Task::actualStartTime, Task::delayCount, Task::getPeriod, lastExecutedTaskId, logTaskDelay, Task::maxDelayMs, Task::scheduledTime.
Referenced by executeTask.
void Scheduler::executeTaskStep(Task *task)
Execute the actual task step.
task Task to execute
References Task::getPeriod, Task::remainingTime, Task::step.
Referenced by executeTask.
void Scheduler::updateTaskStatistics(Task *task, uint32_t execStart)
Update task execution statistics.
task Task to update execStart Execution start time in microseconds
References Task::avgExecTimeUs, Task::maxExecTimeUs, Task::runCount.
Referenced by executeTask.
void Scheduler::updateTimingVariables(Task *task)
Update timing monitoring variables.
task Task that was executed
References Task::getId, lastExecutedTaskId, lastTaskEndTime, systemTime.
Referenced by executeTask.
void Scheduler::checkForTerminatedTask(Task *task)
Check if task should be terminated and remove if needed.
task Task to check
References Task::getState, remove, Task::TERMINATED.
Referenced by executeTask.
void Scheduler::logTaskDelay(Task *task, uint16_t delayMs, uint8_t causingTaskId)
Log task delay with attribution.
task Delayed task delayMs Delay amount in milliseconds causingTaskId ID of task that caused the delay
Referenced by handleTaskTiming.
template void Scheduler::forEachTask< void(*)(Task *)>(Func func)
Iterate through all tasks with a function.
Func Function type that takes Task* parameter func Function to call for each task
References TaskNode::next, TaskNode::task, taskHead.
Referenced by begin, loopOnce, publishMessage.
template Task * Scheduler::findTask< bool(*)(Task *)>(Func predicate)
Find a task using a predicate function.
Func Function type that takes Task* and returns bool predicate Function that returns true for the desired task Pointer to found task, or nullptr if not found
References TaskNode::next, TaskNode::task, taskHead.
Referenced by getTask.
TaskNode * Scheduler::allocateTaskNode(Task *task)
Allocate a TaskNode from the pool.
task Task to wrap in the node Pointer to allocated TaskNode, or nullptr if failed
References freeTaskNodeHead, initializeTaskNodePool, TaskNode::next, TaskNode::task, taskNodePoolCapacity, taskNodePoolInitialized.
Referenced by acquireTaskNode, add.
void Scheduler::deallocateTaskNode(TaskNode *node)
Deallocate a TaskNode back to the pool.
node TaskNode to deallocate
References freeTaskNodeHead, TaskNode::next, TaskNode::task.
Referenced by releaseTaskNode, remove, removeAll.
void Scheduler::logSystemEvent(LogLevel level, const __FlashStringHelper *msg)
Log a system event message.
level Log level msg Message to log
References logMessage.
Referenced by add, begin.
void Scheduler::logTaskExecution(Task *task, uint32_t execTime)
Log a task execution event.
task Task that was executed execTime Execution time in microseconds
bool Scheduler::allocateMsgNodesChunk()
References Scheduler::QueuedMessage::buffer, Scheduler::QueuedMessage::capacity, freeHead, MAX_MESSAGE_POOL_SIZE, Scheduler::QueuedMessage::msg, Scheduler::MsgNode::next, Scheduler::MsgNode::payload, Scheduler::QueuedMessage::targetTaskId, totalNodes.
Referenced by allocateMsgNode, enqueueQueuedMessage.
bool Scheduler::enqueueQueuedMessage(uint8_t targetTaskId, uint8_t topic, uint8_t type, uint16_t arg)
References allocateMsgNodesChunk, freeHead, MAX_MESSAGE_POOL_SIZE, Scheduler::QueuedMessage::msg, msgCount, msgHead, msgTail, Scheduler::MsgNode::next, Scheduler::MsgNode::payload, Scheduler::QueuedMessage::targetTaskId.
Referenced by sendMessage.
bool Scheduler::dequeueQueuedMessage(QueuedMessage &out)
References msgCount, msgHead, msgTail, Scheduler::MsgNode::next, Scheduler::MsgNode::payload.
bool Scheduler::dequeueQueuedMessageNode(MsgNode *&outNode)
References msgCount, msgHead, msgTail, Scheduler::MsgNode::next.
bool Scheduler::initializeTaskNodePool()
References freeTaskNodeHead, Task::getCreatedInstanceCount, TaskNode::next, TaskNode::task, taskNodePoolCapacity, taskNodePoolInitialized.
Referenced by allocateTaskNode.
TaskNode * Scheduler::acquireTaskNode(Task *task)
References allocateTaskNode.
void Scheduler::releaseTaskNode(TaskNode *node)
References deallocateTaskNode.
Scheduler::MsgNode * Scheduler::allocateMsgNode()
References allocateMsgNodesChunk, freeHead, Scheduler::MsgNode::next.
void Scheduler::deallocateMsgNode(MsgNode *node)
References Scheduler::QueuedMessage::buffer, Scheduler::QueuedMessage::capacity, freeHead, Scheduler::QueuedMessage::msg, Scheduler::MsgNode::next, Scheduler::MsgNode::payload, Scheduler::QueuedMessage::targetTaskId.