FsmOS.cpp
MemoryStats fsmos_memory_stats
Referenced by MsgDataPool::allocate, MsgDataPool::deallocate, Scheduler::getMemoryLeakStats, MsgDataPool::initialize.
static void printLogHeader(Scheduler::LogLevel level)
References Scheduler::LOG_ERROR, Scheduler::LOG_INFO, Scheduler::LOG_WARN.
Referenced by logFormattedV.
static void logFormattedV(Scheduler::LogLevel level, const __FlashStringHelper *format, va_list args)
References Scheduler::logMessage, OS, printLogHeader.
Referenced by logDebugf, logErrorf, logInfof, logWarnf.