.TH "Scheduler::QueuedMessage" 3 "Version 1.3.0" "FsmOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Scheduler::QueuedMessage
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBtargetTaskId\fP"
.br
.ti -1c
.RI "MsgData \fBmsg\fP"
.br
.ti -1c
.RI "uint8_t * \fBbuffer\fP"
.br
.ti -1c
.RI "uint8_t \fBcapacity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1455\fP of file \fBFsmOS\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t* Scheduler::QueuedMessage::buffer"

.PP
Definition at line \fB1459\fP of file \fBFsmOS\&.h\fP\&.
.SS "uint8_t Scheduler::QueuedMessage::capacity"

.PP
Definition at line \fB1460\fP of file \fBFsmOS\&.h\fP\&.
.SS "MsgData Scheduler::QueuedMessage::msg"

.PP
Definition at line \fB1458\fP of file \fBFsmOS\&.h\fP\&.
.SS "uint8_t Scheduler::QueuedMessage::targetTaskId"

.PP
Definition at line \fB1457\fP of file \fBFsmOS\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FsmOS from the source code\&.
