.TH "TaskMemoryInfo" 3 "Version 1.3.0" "FsmOS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TaskMemoryInfo \- \fBTask\fP memory information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FsmOS\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBtask_id\fP"
.br
.RI "\fBTask\fP identifier\&. "
.ti -1c
.RI "uint16_t \fBtask_struct_size\fP"
.br
.RI "Size of task structure\&. "
.ti -1c
.RI "uint16_t \fBsubscription_size\fP"
.br
.RI "Size of subscription data\&. "
.ti -1c
.RI "uint16_t \fBqueue_size\fP"
.br
.RI "Size of message queue\&. "
.ti -1c
.RI "uint16_t \fBtotal_allocated\fP"
.br
.RI "Total memory allocated for task\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBTask\fP memory information\&. 

Memory usage statistics for individual tasks 
.PP
Definition at line \fB221\fP of file \fBFsmOS\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint16_t TaskMemoryInfo::queue_size"

.PP
Size of message queue\&. 
.PP
Definition at line \fB226\fP of file \fBFsmOS\&.h\fP\&.
.SS "uint16_t TaskMemoryInfo::subscription_size"

.PP
Size of subscription data\&. 
.PP
Definition at line \fB225\fP of file \fBFsmOS\&.h\fP\&.
.SS "uint8_t TaskMemoryInfo::task_id"

.PP
\fBTask\fP identifier\&. 
.PP
Definition at line \fB223\fP of file \fBFsmOS\&.h\fP\&.
.SS "uint16_t TaskMemoryInfo::task_struct_size"

.PP
Size of task structure\&. 
.PP
Definition at line \fB224\fP of file \fBFsmOS\&.h\fP\&.
.SS "uint16_t TaskMemoryInfo::total_allocated"

.PP
Total memory allocated for task\&. 
.PP
Definition at line \fB227\fP of file \fBFsmOS\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FsmOS from the source code\&.
